(setf *random-state* (make-random-state t))
(defvar numb (+ 1 (random 100)))
(format t "Guess the number! It's from 1 to 100.~%")
(defun do-guess ()
	(finish-output)
	(let ((guess (read)))
		(if (= guess numb) (format t "Correct!")
		(if (< guess numb) 
			(progn (format t "Too low. Try again: ") (do-guess))
			(progn (format t "Too high. Try again: ") (do-guess))))))
(do-guess)
